import type { Metadata } from "next";
import { Roboto_Serif, M_PLUS_1p } from "next/font/google";

import "./globals.css";

import NavBar from "@/components/NavBar";
import { ThemeProvider } from "@/components/theme-provider";


const roboto = Roboto_Serif({
    weight: ["100", "400"],
    subsets: ["latin"],
    variable: "--font-roboto",
    display: "swap",
});

const mplus = M_PLUS_1p({
    weight: ["100", "300", "400"],
    subsets: ["latin"],
    variable: "--font-mplus",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja">
            <body className={`${roboto.variable} ${mplus.variable} h-full w-full m-0`}>
                <ThemeProvider
                attribute="class"
                defaultTheme="light"
                enableSystem={true}
                storageKey="theme"
                >
                    <header>
                        <NavBar />
                    </header>
                    <main className="h-fit px-2 py-3 relative overflow-x-hidden">
                        {children}
                    </main>
                </ThemeProvider>
            </body>
        </html>
    );
}
