import type { Metadata } from "next";
import { Roboto_Serif } from "next/font/google";

import "./globals.css";

import NavBar from "@/components/NavBar";


const roboto = Roboto_Serif({
    weight: "100",
    subsets: ["latin"],
    variable: "--font-roboto",
    display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${roboto.variable}`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
